baseURL = "https://github.com/jacob-blomq/my_hugo_resume.git"
languageCode = "en-us"
title = "My Hugo Resume"
theme = "resume"
publishDir = "docs"

[params]
    firstName = "Jacob"
    lastName = "Blomquist"
    address = "1105 Union Street, Manchester, NH"
    phone = "603-657-5325"
    profileImage = "img/me.png"
    email = "jacob@family.blomquist.org"
    description = "Passionate and motivated individual with experience with Linux and Windows systems, object-oriented programming languages, HTML and CSS, and System Administration operations."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/jacob-blomquist-371515131"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/jacob-blomq"

